project:
  type: website
  resources:
    - google96bc4eb628ee8060.html

website:
  title: "Giovanni Cuttica"
  description: "Applied economics: public economics, policy evaluation, and applied econometrics"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: papers.qmd
        text: Papers and Projects
      - href: notes.qmd
        text: Notes
      - href: data.qmd
        text: Data
      - href: musings.qmd
        text: Musings

format:
  html:
    theme:
      - flatly
    css: styles.css
    toc: false
    grid:
      body-width: 850px

execute:
  freeze: auto
